services:
  redpanda:
    image: redpandadata/redpanda:latest
    container_name: finmesh-redpanda
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp=1
      - --memory=1G
      - --reserve-memory=0M
      - --node-id=0
      - --check=false
      - --kafka-addr=INTERNAL://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr=INTERNAL://redpanda:29092,OUTSIDE://localhost:9092
    ports:
      - "9092:9092"

  redpanda-console:
    image: redpandadata/console:latest
    container_name: finmesh-console
    depends_on:
      - redpanda
    ports:
      - "8080:8080"
    environment:
      KAFKA_BROKERS: redpanda:29092

  postgres:
    image: postgres:16
    container_name: finmesh-postgres
    environment:
      POSTGRES_USER: finmesh
      POSTGRES_PASSWORD: finmesh
      POSTGRES_DB: finmesh
    ports:
      - "5433:5432"
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
    container_name: finmesh-elasticsearch
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.3
    container_name: finmesh-kibana
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - "5601:5601"